USE EDA;

-- Find the total customers by countries
SELECT country, COUNT(customer_key) as total_customers
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT gender, COUNT(customer_key) as number_of_customers
FROM dim_customers
GROUP BY gender
ORDER BY number_of_customers DESC;

-- Find total products by category
SELECT category, COUNT(product_key) as total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Average cost in each category
SELECT category, AVG(cost) as average_cost
FROM dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated by each category
SELECT 
	pd.category,
    SUM(sf.sales_amount) as total_revenue
FROM dim_products as pd
LEFT JOIN fact_sales as sf
ON pd.product_key = sf.product_key
GROUP BY pd.category
HAVING SUM(sf.sales_amount) > 0
ORDER BY total_revenue DESC;

-- what is the total revenue generated by each customer
SELECT
	cd.customer_key,
    cd.first_name,
    cd.last_name,
    SUM(sf.sales_amount) as total_revenue
FROM dim_customers as cd
LEFT JOIN fact_sales as sf
ON cd.customer_key = sf.customer_key
GROUP BY cd.customer_key,cd.first_name,cd.last_name
HAVING SUM(sf.sales_amount) > 0
ORDER BY total_revenue DESC;

-- what is the distribution of sold items accross the country
SELECT
	cd.country,
    SUM(sf.quantity) as total_items
FROM dim_customers as cd
LEFT JOIN fact_sales as sf
On cd.customer_key = sf.customer_key
GROUP BY cd.country
ORDER BY total_items DESC;


